erDiagram

  UTILISATEUR {
    int id PK
    string nom
    string email
    string mot_de_passe
    string role
    %% role: agent | modo | admin
  }

  CATEGORIE {
    int id PK
    string nom
    int parent_id FK
    int ordre_affichage
  }

  PROBLEME {
    int id PK
    string titre
    string description
    string image_url
    int categorie_id FK
  }

  ACTUALITE {
    int id PK
    string titre
    string contenu
    datetime date_creation
    string type
    int auteur_id FK
  }

  NOTIFICATION {
    int id PK
    int utilisateur_id FK
    int actualite_id FK
    string statut
  }

  ABONNEMENT {
    int utilisateur_id PK
    int categorie_id PK
  }

  FAVORIS {
    int utilisateur_id PK
    int categorie_id PK
  }

  CATEGORIE ||--o{ CATEGORIE : parent
  CATEGORIE ||--o{ PROBLEME : contient
  UTILISATEUR ||--o{ PROBLEME : consulte
  UTILISATEUR ||--o{ ABONNEMENT : s_abonne
  CATEGORIE ||--o{ ABONNEMENT : est_abonnement
  UTILISATEUR ||--o{ FAVORIS : met_en_favori
  CATEGORIE ||--o{ FAVORIS : est_favori
  UTILISATEUR ||--o{ ACTUALITE : cree
  ACTUALITE ||--o{ NOTIFICATION : genere
  UTILISATEUR ||--o{ NOTIFICATION : recoit