# Application Properties for Assist62API

spring.application.name=Assist62API

# DB Configuration
spring.datasource.driverClassName = org.postgresql.Driver

spring.datasource.url = jdbc:postgresql://localhost:5432/assist62
spring.jpa.hibernate.ddl-auto = update

# branch
app.branch.status=dev

# Pour le développement
app.cors.allowed-origins.dev=http://localhost:1420


# Pour la production
app.cors.allowed-origins.prod=https://votredomaine.com

# Auth
security.jwt.secret-key = N2QzYzVjZTYtZGYyNy00YjZmLWE5MmMtZDEyNDAyZjkxY2M4NDYyMWRiYjgtYjM5Mi00MjQ4LWIzMjItYjM5YjM5ZDIzZDIy
security.jwt.expiration-time = 36000000
